### ISSUE TITLE
More data properties for projects list endpoint

### ISSUE THREAD

**Issue by dereklieu** [map-egypt/api#14]
To make the project card:

<img width="334" alt="screen shot 2016-11-23 at 11 50 07 am" src="https://cloud.githubusercontent.com/assets/1590802/20576898/aee039d8-b174-11e6-85a9-faf59252f68d.png">

I still need:

- description
- percent complete
- funding
- and households

cc @felskia

**Comment by felskia** [comment]
@dereklieu is this stuff not in the API? We have that information for this project. 

Description: this is there
Percent Complete: They want us to derive this from actual start date and actual end date
Funding: they want us to take the money from budget, add it up and put the full number there
Households: We have this info too under Num. of Beneficiaries. Also, FYI households won't always be households. It might be something like farmers served. But that is why we have a unit field there.

**Comment by dereklieu** [comment]
It is, just not in this endpoint (it's in the detailed project endpoint but I need it to in the project list endpoint).

**Comment by dereklieu** [comment]
@kamicut this still needs the description and the households.

**Comment by dereklieu** [comment]
Also, the project page lists projects that have the same `sds_indicator` property. To support this, we will need to include the `sds_indicator` array along with the project-list endpoint, or include a related projects field with the single project endpoint. Up to you on how to do this, I think I would support just including the `sds_indicator` with each project.

**Comment by kamicut** [comment]
@dereklieu this should be fixed by #16

**Comment by dereklieu** [comment]
@kamicut `description` and `number_served` works, but I'm getting `sds_indicators: null` for all the projects.
